# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: josh tregenza
email: josh@joshtregenza.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm Josh. I'm a designer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joshtregenza.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: joshtregenza
github_username:  jtregenza
instagram_username: josh_tregenza
dribbble_username: joshtregenza

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: :title
sass:
    style: :compressed



# Default Settings
collections:
  work:
    output: true
    permalink: /work/:title/
  projects:
    output: true
    permalink: /projects/:title/
  podcast:
    output: true
    permalink: /podcast/:title/
  process:
    output: true
    permalink: /process/:title/
  dev-log:
    output: true
    permalink: /dev-log/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: "Josh Tregenza"
      category: writing
        
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: page
      author: "Josh Tregenza"
        
    scope:
      path: "work"
      type: work
    values:
      layout: page
      author: "Josh Tregenza"

    scope:
      path: "projects"
      type: project
    values:
      layout: project-post
      author: "Josh Tregenza"

    scope:
      path: "process"
      type: process
    values:
      layout: page
      author: "Josh Tregenza"

    scope:
      path: "dev-log"
      type: dev-log
    values:
      layout: page
      author: "Josh Tregenza"
