# Site settings
title: Josh Tregenza | Designer
email: josh@joshtregenza.com
description: >
  I’m an autodidact designer that is curious in the interactions between people and how design plays a part in that communication. I code and build sites with the user at the forefront.
url: "http://www.joshtregenza.com" # the base hostname & protocol for your site
twitter_username: joshtregenza
github_username:  jtregenza

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn.mkd.md"
permalink: :title
paginate: 4
paginate_path: "/blog/page:num/"

sass:
    style: :compressed

# Default Settings
collections:
  case_studies:
    output: true
    permalink: /case-studies/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Josh Tregenza
      category: writing
        -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "new_default"
      author: Josh Tregenza
        -
    scope:
      path: ""
      type: case_studies
    values:
      layout: "new_default"

