# Site settings
title: Josh Tregenza | Designer
email: josh@joshtregenza.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a designer of sites, ideas and processes that make my life more efficient and my clients. This site and the ones featured in this site have been designer and developed by myself using a range of standards based systems. 
url: "http://www.joshtregenza.com" # the base hostname & protocol for your site
twitter_username: joshtregenza
github_username:  jtregenza

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn.mkd.md"
permalink: :title
paginate: 4
paginate_path: "/blog/page:num/"

sass:
    style: :compressed