# Site settings
title: josh tregenza // designer
email: josh@joshtregenza.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Josh. I'm a designer. I use my skills to help you make more money.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joshtregenza.com" # the base hostname & protocol for your site
twitter_username: joshtregenza
github_username:  jtregenza
instagram_username: josh_tregenza
dribbble_username: joshtregenza

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: :title
sass:
    style: :compressed


#Gems
gems: [jekyll-paginate]


# Default Settings
collections:
  case_studies:
    output: true
    permalink: /case_studies/:title/
  projects:
    output: true
    permalink: /projects/:title/
  podcast:
    output: true
    permalink: /podcast/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: "Josh Tregenza"
      category: writing
        
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: page
      author: "Josh Tregenza"
        
    scope:
      path: "case_studies"
      type: case_studies
    values:
      layout: page
      author: "Josh Tregenza"

    scope:
      path: "projects"
      type: projects
    values:
      layout: page
      author: "Josh Tregenza"

    scope:
      path: "podcast"
      type: podcast
    values:
      layout: page
      author: "Josh Tregenza"

    

