
# Site settings
title: Josh Tregenza | Designer
email: josh@joshtregenza.com
description: > # this means to ignore newlines until "baseurl:"
  I build things with people just like you. Talk to me about web design, pixel art and low poly art.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joshtregenza.com" # the base hostname & protocol for your site
twitter_username: joshtregenza
github_username:  jtregenza
instagram_username: josh_tregenza
dribbble_username: JTreg

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn.mkd.md"
permalink: :title
sass:
    style: :compressed

# Default Settings
collections:
  case_studies:
    output: true
    permalink: /case-studies/:title/
  art:
    output: true
    permalink: /art/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Josh Tregenza
      category: writing
        -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
      author: Josh Tregenza
        -
    scope:
      path: ""
      type: case_studies
    values:
      layout: "page"
      author: Josh Tregenza


